server:
  port: "8090"
  host: "localhost"

store:
  segments_per_cpu: 4
  cleanup_interval_seconds: 1
  wal_file_path: wal.log
  snapshot_file_path: snapshot.db
  wal_flush_interval_seconds: 1
  snapshot_interval_seconds: 120
  wal_max_size_bytes: 450
  wal_max_files: 5
  wal_directory: wal
